# Generated by Django 3.2.11 on 2022-01-31 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='create_user',
        ),
    ]
