# Generated by Django 3.2.11 on 2022-01-29 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_music'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
